# Video of brain spinning with all clusters, organized by insertion

In [1]:
import oursin as urchin

In [2]:
urchin.setup()

(URN) connected to server
Login sent with ID: a4dd55d6, copy this ID into the renderer to connect.


packet queue is empty, aborting


(URN) disconnected from server
(URN) connected to server
Login sent with ID: a4dd55d6, copy this ID into the renderer to connect.
(URN) disconnected from server
(URN) connected to server
Login sent with ID: a4dd55d6, copy this ID into the renderer to connect.


packet queue is empty, aborting


(URN) disconnected from server
(URN) connected to server
Login sent with ID: a4dd55d6, copy this ID into the renderer to connect.
(URN) disconnected from server
(URN) connected to server
Login sent with ID: a4dd55d6, copy this ID into the renderer to connect.


In [1]:
# from brainwidemap import bwm_query, bwm_units
# from one.api import ONE

# one = ONE(base_url='https://openalyx.internationalbrainlab.org')
# # Dataframe with info on all sessions and probes released for the BWM
# bwm_df = bwm_query(one)
# # Dataframe with information on all neurons used in the analyses in the BWM paper
# unit_df = bwm_units(one)

c:\Users\Dan\anaconda3\envs\iblenv\lib\site-packages\neurodsp\__init__.py:5: FutureWarning: neurodsp has been renamed to ibldsp and the old name will be deprecated on 01-Sep-2024.
  warn(
c:\Users\Dan\anaconda3\envs\iblenv\lib\site-packages\ibllib\atlas\__init__.py:202: DeprecationWarning: ibllib.atlas is deprecated. Please install iblatlas using "pip install iblatlas" and use this module instead
  warnings.warn('ibllib.atlas is deprecated. Please install iblatlas using "pip install iblatlas" and use '
c:\Users\Dan\anaconda3\envs\iblenv\lib\site-packages\one\params.py:184: UserWarning: Warning: the directory provided is already a cache for another URL.
  warnings.warn('Warning: the directory provided is already a cache for another URL.')


In [4]:
# bwm_df.to_parquet('bwm_df.pqt')
# unit_df.to_parquet('unit_df.pqt')

In [8]:
import pandas as pd

In [9]:
bwm_df = pd.read_parquet('bwm_df.pqt')
unit_df = pd.read_parquet('unit_df.pqt')

In [ ]:

# from pathlib import Path

# from one.api import ONE
# import ephys_atlas.data

# LABEL = '2024_W04'  # 2023_W51_autism for example would return the autism dataset features
# LOCAL_DATA_PATH = Path('C:/scratch/')
# one = ONE(base_url="https://alyx.internationalbrainlab.org", mode='local')

# df_raw_features, df_clusters, df_channels, df_probes = ephys_atlas.data.download_tables(
#     label=LABEL, local_path=LOCAL_DATA_PATH, one=one)
# # df_raw_features, df_clusters, df_channels = load_tables(local_path=FOLDER_GDRIVE)

# # df_depths = ephys_atlas.data.compute_depth_dataframe(df_raw_features, df_clusters, df_channels)
# df_voltage = df_raw_features.merge(df_channels, left_index=True, right_index=True)

In [28]:
bwm_df.loc[bwm_df['lab'] == 'hoferlab', 'lab'] = 'hoferflogellab'
bwm_df.loc[bwm_df['lab'] == 'mrsicflogellab', 'lab'] = 'hoferflogellab'

In [10]:
from iblatlas import atlas
aa = atlas.AllenAtlas()
from iblatlas.regions import BrainRegions
br = BrainRegions()
import numpy as np
import pandas as pd
import time
import seaborn as sns

In [11]:
def hex_to_rgb(hex_color):
    # Remove '#' if present
    if hex_color.startswith('#'):
        hex_color = hex_color[1:]

    # Convert hex to RGB
    red = int(hex_color[0:2], 16) / 255.0
    green = int(hex_color[2:4], 16) / 255.0
    blue = int(hex_color[4:6], 16) / 255.0

    return red, green, blue

In [30]:
ulabs = np.unique(bwm_df.lab)

In [32]:
lab_data = []

id2color = {}

for lab in ulabs:
    pids = bwm_df.pid[bwm_df.lab == lab]
    
    # print((lab, len(pids)))


    coords = []

    for pid in pids:
        units = unit_df[unit_df.pid==pid]
        # print(len(units))
        for i, unit in units.iterrows():
            coord = aa.xyz2ccf([unit.x, unit.y, unit.z])
            if unit.atlas_id in id2color.keys():
                color = id2color[unit.atlas_id]
            else:
                color = hex_to_rgb(aa.regions.hexcolor[aa.regions.id2index(unit.atlas_id)[1][0][0]])
                id2color[unit.atlas_id] = color
            coords.append([coord, color])

    lab_df = pd.DataFrame(columns=['mlapdv', 'color'], data=coords)

    lab_data.append(lab_df)

In [31]:
# contributions
print(ulabs)

['angelakilab' 'churchlandlab' 'churchlandlab_ucla' 'cortexlab' 'danlab'
 'hausserlab' 'hoferflogellab' 'mainenlab' 'steinmetzlab' 'wittenlab'
 'zadorlab']


In [23]:
# institution_map = {'cortexlab': 'UCL', 'mainenlab': 'CCU', 'zadorlab': 'CSHL (Z)',
#                        'churchlandlab': 'CSHL (C)', 'angelakilab': 'NYU',
#                        'wittenlab': 'Princeton', 'hoferlab': 'SWC', 'mrsicflogellab': 'SWC',
#                        'danlab': 'Berkeley', 'steinmetzlab': 'UW', 'churchlandlab_ucla': 'UCLA', 'hausserlab':'UCL'}
institution_map = {'cortexlab': 'Carandini & Harris Labs (University College London)', 'mainenlab': 'Mainen Lab (Champalimaud Center for the Unknown)',
                   'zadorlab': 'Zador Lab (Cold Spring Harbor)', 'churchlandlab': 'Churchland Lab (Cold Spring Harbor)',
                   'angelakilab': 'Angelaki Lab (New York University)', 'wittenlab': 'Witten Lab (Princeton University)', 
                   'hoferflogellab': 'Hofer & Mrsic-Flogel Labs (Sainsbury-Wellcome Centre)',
                   'danlab': 'Dan Lab (University of California, Berkeley)', 'steinmetzlab': 'Steinmetz Lab (University of Washington)',
                   'churchlandlab_ucla': 'Churchland Lab (University of California, Los Angeles)', 'hausserlab': 'Hausser Lab (University College London)'}

In [33]:
names_clean = [institution_map[lab] for lab in ulabs]

In [34]:
names_clean

['Angelaki Lab (New York University)',
 'Churchland Lab (Cold Spring Harbor)',
 'Churchland Lab (University of California, Los Angeles)',
 'Carandini & Harris Labs (University College London)',
 'Dan Lab (University of California, Berkeley)',
 'Hausser Lab (University College London)',
 'Hofer & Mrsic-Flogel Labs (Sainsbury-Wellcome Centre)',
 'Mainen Lab (Champalimaud Center for the Unknown)',
 'Steinmetz Lab (University of Washington)',
 'Witten Lab (Princeton University)',
 'Zador Lab (Cold Spring Harbor)']

In [35]:
names_contribs = ['Julius Benson, Jean-Paul Noel',
                  'Anne Urai, Anup Khanal',
                  'Anup Khanal, Felicia Davatolhagh',
                  'Karolina Socha',
                  'Fei Hu',
                  'Petrina Lau',
                  'Nathaniel Miska',
                  'Guido Meijer, Joana Catarino',
                  'Noam Roth',
                  'Alejandro Pan-Vazquez',
                  'Christpher Krasniak']

In [36]:
lab_colors = np.concatenate([sns.color_palette("Dark2"), sns.color_palette('Set2')])

In [37]:
# re-order everything from west to east 
# original order
# 0 NYU, 1 CSHL-C, 2 UCLA, 3 UCL, 4 Berkeley, 5 UCL, 6 SWC, 7 Champalimaud, 8 UW, 9 Princeton, 10 CSHL-Z
order = [8, 4, 2, 9, 0, 10, 1, 7, 5, 6, 3]

In [38]:
lab_data = [lab_data[i] for i in order]
names_clean = [names_clean[i] for i in order]
names_contribs = [names_contribs[i] for i in order]
lab_colors = [lab_colors[i] for i in order]

In [43]:
[print(name) for name in names_clean]

Steinmetz Lab (University of Washington)
Dan Lab (University of California, Berkeley)
Churchland Lab (University of California, Los Angeles)
Witten Lab (Princeton University)
Angelaki Lab (New York University)
Zador Lab (Cold Spring Harbor)
Churchland Lab (Cold Spring Harbor)
Mainen Lab (Champalimaud Center for the Unknown)
Hausser Lab (University College London)
Hofer & Mrsic-Flogel Labs (Sainsbury-Wellcome Centre)
Carandini & Harris Labs (University College London)


[None, None, None, None, None, None, None, None, None, None, None]

In [41]:
for i in np.arange(0, len(lab_data)):
    print((lab_colors[i]))

[0.4        0.76078431 0.64705882]
[0.4        0.65098039 0.11764706]
[0.45882353 0.43921569 0.70196078]
[0.98823529 0.55294118 0.38431373]
[0.10588235 0.61960784 0.46666667]
[0.55294118 0.62745098 0.79607843]
[0.85098039 0.37254902 0.00784314]
[0.4 0.4 0.4]
[0.90196078 0.67058824 0.00784314]
[0.65098039 0.4627451  0.11372549]
[0.90588235 0.16078431 0.54117647]


In [59]:
import oursin as urchin
urchin.setup(id='test')

(urchin) Client is already connected. Use ID: test


In [88]:
# Load root
urchin.ccf25.load()

(Warning) Atlas was already loaded, the renderer can have issues if you try to load an atlas twice.


In [89]:
urchin.ccf25.root.set_visibility(True, side=urchin.utils.Side.FULL)
urchin.ccf25.root.set_color([0,0,0])
urchin.ccf25.root.set_material('transparent-lit')
urchin.ccf25.root.set_alpha(0.15)

In [90]:
urchin.camera.main.set_rotation([-45, 0, 0])
urchin.camera.set_brain_rotation(225)
urchin.camera.main.set_zoom(55)
urchin.camera.main.set_mode('perspective')
urchin.camera.main.set_pan(5,5)

In [91]:
text = urchin.text.Text()
text.set_color('#ffffff')
text.set_font_size(85)

contrib_text = urchin.text.Text()
contrib_text.set_color('#ffffff')
contrib_text.set_font_size(60)

In [92]:
text.set_color('#000000')
contrib_text.set_color('#000000')
text.set_text("test")
contrib_text.set_text("test")

In [93]:

text.set_position([-0.92, 0.93])
contrib_text.set_position([-0.92, 0.8])

In [94]:
# Pre-create all neurons and store them in lists
all_meshes = []
all_colors = []
neurons_by_lab = {}

for i, lab_df in enumerate(lab_data):
    
    ccolor = list(lab_colors[i])
    meshes = urchin.meshes.create(len(lab_df))
    all_meshes = all_meshes + meshes
    positions = []
    colors = []
    
    for j, row in lab_df.iterrows():
        positions.append([row.mlapdv[1], row.mlapdv[0], row.mlapdv[2]])
        colors.append(ccolor)
        all_colors.append(row.color)
    
    urchin.meshes.set_positions(meshes, positions)
    urchin.meshes.set_colors(meshes, colors)
    urchin.meshes.set_scales(meshes, [[0,0,0]]*len(meshes))

    neurons_by_lab[i] = meshes

In [95]:
s_per_build = 2
s_per_lab = 3
s_pause = 1
s_end = 6
fps = 30

lab_frames = fps*len(ulabs)*s_per_lab
pause_frames = lab_frames + s_pause * fps
total_frames = pause_frames + s_end * fps
total_s = s_per_lab*len(ulabs) + s_pause + s_end
print((lab_frames, pause_frames, total_frames))

frames_per_build = s_per_build * fps
frames_per_lab = s_per_lab*fps
lab_meshes = []

pause_set = False
end_set = False

def set_view(frame):   
    global lab_idx, ccolor, lab_meshes, lab_frames, pause_frames, pause_set, pause_frames, end_set

    urchin.camera.set_brain_rotation(225 + frame * 0.5)
    
    if (frame < lab_frames):
        if np.mod(frame, frames_per_lab) == 0:
            if lab_meshes:
                urchin.meshes.set_scales(lab_meshes, [[0,0,0]]*len(lab_meshes))

            lab_idx = int(np.floor(frame / frames_per_lab))
            ccolor = list(lab_colors[lab_idx])

            text.set_text(names_clean[lab_idx])
            text.set_color(ccolor)

            contrib_text.set_text(names_contribs[lab_idx])
            contrib_text.set_color(ccolor)

            lab_meshes = neurons_by_lab[lab_idx]

        perc = np.min([np.mod(frame, frames_per_lab) / frames_per_build, 1])
        num_meshes = int(np.floor(len(lab_meshes) * perc))

        urchin.meshes.set_scales(lab_meshes[0:num_meshes], [[0.04, 0.04, 0.04]]*num_meshes)
    
    elif (frame < pause_frames):
        if not pause_set:
            pause_set = True

            text.set_text("")
            contrib_text.set_text("")
            
            urchin.meshes.set_scales(lab_meshes, [[0, 0, 0]]*len(lab_meshes))

    else:
        if not end_set:
            end_set = True

            text.set_text("International Brain Laboratory")
            text.set_color([0,0,0])
            contrib_text.set_text("Brain Wide Map")
            contrib_text.set_color([0,0,0])
            urchin.meshes.set_colors(all_meshes, all_colors)
            urchin.meshes.set_scales(all_meshes, [[0.04, 0.04, 0.04]]*len(all_meshes))

all_meshes = []
for i in np.arange(0,len(neurons_by_lab)):
    all_meshes = all_meshes + neurons_by_lab[i]

(990, 1020, 1200)


In [84]:
# test mode
for i in np.arange(0, total_frames):
    if np.mod(i, 10)==0:
        set_view(i)
        time.sleep(0.2)

In [96]:
await urchin.camera.main.capture_video(file_name='mov2.mp4', callback=set_view, duration=total_s)

(Camera receive) Camera CameraMain received an image
(Camera receive) CameraMain complete
(Camera receive) Camera CameraMain received an image
(Camera receive) CameraMain complete
(Camera receive) Camera CameraMain received an image
(Camera receive) CameraMain complete
(Camera receive) Camera CameraMain received an image
(Camera receive) CameraMain complete
(Camera receive) Camera CameraMain received an image
(Camera receive) CameraMain complete
(Camera receive) Camera CameraMain received an image
(Camera receive) CameraMain complete
(Camera receive) Camera CameraMain received an image
(Camera receive) CameraMain complete
(Camera receive) Camera CameraMain received an image
(Camera receive) CameraMain complete
(Camera receive) Camera CameraMain received an image
(Camera receive) CameraMain complete
(Camera receive) Camera CameraMain received an image
(Camera receive) CameraMain complete
(Camera receive) Camera CameraMain received an image
(Camera receive) CameraMain complete
(Camera re

packet queue is empty, aborting


(URN) disconnected from server
(URN) connected to server
Login sent with ID: test, copy this ID into the renderer to connect.
(URN) disconnected from server
(URN) connected to server
Login sent with ID: test, copy this ID into the renderer to connect.
(URN) disconnected from server
(URN) connected to server
Login sent with ID: test, copy this ID into the renderer to connect.


packet queue is empty, aborting


(URN) disconnected from server
(URN) connected to server
Login sent with ID: test, copy this ID into the renderer to connect.
(URN) disconnected from server
(URN) connected to server
Login sent with ID: test, copy this ID into the renderer to connect.


packet queue is empty, aborting


(URN) disconnected from server
(URN) connected to server
Login sent with ID: test, copy this ID into the renderer to connect.
(URN) disconnected from server
(URN) connected to server
Login sent with ID: test, copy this ID into the renderer to connect.
(URN) disconnected from server
(URN) connected to server
Login sent with ID: test, copy this ID into the renderer to connect.


packet queue is empty, aborting
